### ISSUE TITLE
two recent wontfix EoP by GPZ

### ISSUE THREAD

**Issue by TearsOfSky** [cfalta/MicrosoftWontFixList#6] opened 2021-07-29 22:00 UTC
Issue 2207: Windows: WFP Default Rules AppContainer Capability Bypass EoP 
https://bugs.chromium.org/p/project-zero/issues/detail?id=2207

 Issue 2194: Windows: CreateProcessWithLogon Write Restricted Service EoP 
https://bugs.chromium.org/p/project-zero/issues/detail?id=2194

**Comment by cfalta** [comment] 2021-08-02 15:35
Thank you for your feedback :-) This list was intended to be a summary of what happend in July 2021 and I decided I'll keep it that way, because I honestly think I don't have the energy to maintain an up-to-date list of ALL won't fixes Microsoft has to offer. 
I added a remark to clarify this.

**Closed as completed by cfalta** 2021-08-02 15:35 UTC
